name: Test CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Connect to Server
      uses: Biniou01/epsi-password-manager@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
